### PR TITLE
add SlaveOk support at the connection level

### PR DESCRIPTION
**Pull request by willm**
I've implemented reading from slaves. I've made a few assumptions which I'm happy to change if people object.
* Collections, indexes, users and functions are *always* loaded with the slaveOk option
* When creating connections, there is a new slaveOk option
* If the slaveOk option is on for your connection, the shell window will open allowing you to read from secondary nodes.

### CODE REVIEW

**Comment by willm** [comment]
Thanks for your feedback @stennie. I don't remember off the top of my head why I removed getCollectionNames, I'll take a look next week.

**Comment by willm** [comment]
@stennie do you have any further feedback? It seems this feature would be useful.

**Comment by stennie** [comment]
@willm I'd like to merge this in with changes for the [0.9.0 release](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0), which includes updates to the MongoDB 3.0 shell.

Definitely a useful feature, but the patch will have to be adjusted given code changes. I'll comment here when the 3.0 changes are merged.

**Comment by piotrekkmt** [comment]
Hey, any time schedule on a 0.9 release that can handle Mongo 3.0?

**Comment by schetnikovich** [comment]
Support for connection to Secondary members in Replica sets is implemented starting from version 0.9.0 RC4. Implementation is against MongoDB 3.2 shell. 

@willm, thank you for your help! Now, when we have support for MongoDB 3.2 and committed to push Robomongo forward, we should handle PRs much faster. Thank you again!

**Pull request closed without merging**
